services:
  - type: web
    name: dormitory-system-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: FRONTEND_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
